<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <AssemblyName>Knapcode.TorSharp</AssemblyName>
    <RootNamespace>Knapcode.TorSharp</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>

    <PackageId>Knapcode.TorSharp</PackageId>
    <Version>$(TorSharpVersion)</Version>
    <Authors>Joel Verhagen</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Use Tor for your C# HTTP clients. Use Privoxy or .NET 6+ SOCKS support to proxy HTTP traffic.</Description>
    <PackageProjectUrl>https://github.com/joelverhagen/TorSharp</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright © 2024 Joel Verhagen</Copyright>
    <PackageTags>tor proxy privoxy http socks socks5 onion router https anonymize anonymous</PackageTags>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReleaseNotes>See CHANGELOG.md at https://github.com/joelverhagen/TorSharp/blob/master/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConfigureAwaitChecker.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SharpCompress" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Syndication" />
  </ItemGroup>

  <!-- LibraryImport source generator emits unsafe code on .NET 7+ -->
  <PropertyGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <BeforePack>OutputVersion</BeforePack>
  </PropertyGroup>

  <Target Name="OutputVersion">
    <Message Text="TorSharp version: $(TorSharpVersion)" Importance="high" />
  </Target>

</Project>
