name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      build_stable_version:
        type: boolean
        description: "Build the stable version of the package for release"
        required: false
        default: false
      run_sample:
        type: boolean
        description: "Run the sample app"
        required: false
        default: false
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, windows-2025, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    env:
      TORSHARP_TEST_CACHE: ${{ github.workspace }}/tests/cache

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache test downloads
        uses: actions/cache@v4
        with:
          path: tests/cache
          key: ${{ matrix.os }}-torsharp-test

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Install Privoxy dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libbrotli1 libmbedtls14

      - name: Run sample
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_sample }}
        run: |
          date
          dotnet run --project samples/TorSharp.Sandbox --framework net9.0

      - name: Setup tmate session (Linux)
        if: ${{ runner.os == 'Linux' && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: dotnet test --configuration Release --no-restore --no-build --logger "console;verbosity=normal" --blame-hang-timeout 30m

      - name: Format
        run: dotnet format --no-restore --verify-no-changes

      - name: Pack
        if: matrix.os == 'windows-2025'
        run: dotnet pack --configuration Release --no-restore --no-build
        env:
          BUILD_STABLE_VERSION: ${{ inputs.build_stable_version }}

      - name: Upload artifacts
        if: matrix.os == 'windows-2025'
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            artifacts/TorSharp/bin/Release/*.nupkg

  publish:
    needs: build
    if: github.event_name == 'push'
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages

      - name: Push artifacts
        run: dotnet nuget push packages\*.nupkg -s https://nuget.pkg.github.com/joelverhagen/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
